services:
  postgres:
    image: postgres:16
    container_name: zenith-psychology-postgres
    environment:
      POSTGRES_DB: ${KEY_POSTGRES_URL}
      POSTGRES_USER: ${KEY_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${KEY_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
