spring.application.name=Zenith Psychology Manager

spring.datasource.url=jdbc:postgresql://localhost:5432/zenith_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:change-this-secret-before-production-change-this-secret-before-production}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:720}

server.error.include-message=always
