spring.application.name=Zenith Psychology Manager
spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${KEY_POSTGRES_URL}
spring.datasource.username=${KEY_POSTGRES_USERNAME}
spring.datasource.password=${KEY_POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:change-this-secret-before-production-change-this-secret-before-production}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:720}

server.error.include-message=always
